from __future__ import annotations

from copy import deepcopy
from typing import Dict, List

from app.models import TaskName


def _case(
    patient_id: str,
    complaint: str,
    age_years: int,
    arrival_mode: str,
    mental_status: str,
    pain_score: int,
    vitals: dict,
    waiting_room: int,
    available_beds: int,
    queue_by_acuity: list[int],
    elapsed_shift_minutes: int,
    gold_category: int,
    requires_resus: bool,
    bed_required: bool,
    notes: list[str],
) -> dict:
    return {
        "patient_id": patient_id,
        "patient_complaint": complaint,
        "age_years": age_years,
        "arrival_mode": arrival_mode,
        "mental_status": mental_status,
        "pain_score": pain_score,
        "vitals": vitals,
        "waiting_room": waiting_room,
        "available_beds": available_beds,
        "queue_by_acuity": queue_by_acuity,
        "elapsed_shift_minutes": elapsed_shift_minutes,
        "gold_category": gold_category,
        "requires_resus": requires_resus,
        "bed_required": bed_required,
        "notes": notes,
    }


TASK_EPISODES: Dict[TaskName, List[List[dict]]] = {
    TaskName.EASY: [
        [
            _case(
                "easy-acs",
                "Crushing chest pain radiating to left arm with diaphoresis",
                58,
                "walk-in",
                "anxious but oriented",
                9,
                {
                    "heart_rate": 118,
                    "blood_pressure_sys": 84,
                    "blood_pressure_dia": 56,
                    "oxygen_saturation": 91,
                    "respiratory_rate": 26,
                    "temperature_c": 36.8,
                },
                2,
                1,
                [0, 0, 1, 1, 0],
                35,
                1,
                True,
                True,
                ["Possible acute coronary syndrome", "Profound hypotension"],
            )
        ],
        [
            _case(
                "easy-stroke",
                "Sudden facial droop and slurred speech for 20 minutes",
                71,
                "wheelchair",
                "confused",
                3,
                {
                    "heart_rate": 94,
                    "blood_pressure_sys": 176,
                    "blood_pressure_dia": 98,
                    "oxygen_saturation": 95,
                    "respiratory_rate": 20,
                    "temperature_c": 36.9,
                },
                1,
                1,
                [0, 1, 0, 0, 0],
                42,
                2,
                True,
                True,
                ["Possible stroke alert", "Time-sensitive neuro pathway"],
            )
        ],
        [
            _case(
                "easy-ankle",
                "Twisted ankle during football practice, able to bear some weight",
                19,
                "walk-in",
                "alert",
                5,
                {
                    "heart_rate": 86,
                    "blood_pressure_sys": 124,
                    "blood_pressure_dia": 78,
                    "oxygen_saturation": 99,
                    "respiratory_rate": 16,
                    "temperature_c": 36.7,
                },
                3,
                2,
                [0, 0, 1, 1, 2],
                60,
                5,
                False,
                False,
                ["Stable musculoskeletal injury", "Low immediate risk"],
            )
        ],
    ],
    TaskName.MEDIUM: [
        [
            _case(
                "med-asthma",
                "Shortness of breath with audible wheeze and accessory muscle use",
                26,
                "walk-in",
                "anxious",
                6,
                {
                    "heart_rate": 124,
                    "blood_pressure_sys": 96,
                    "blood_pressure_dia": 64,
                    "oxygen_saturation": 88,
                    "respiratory_rate": 30,
                    "temperature_c": 37.1,
                },
                11,
                0,
                [0, 2, 4, 3, 2],
                340,
                2,
                True,
                False,
                ["Severe asthma exacerbation", "No monitored beds currently free"],
            )
        ],
        [
            _case(
                "med-sepsis",
                "Fever, rigors, hypotension, and new confusion",
                67,
                "ambulance",
                "drowsy",
                4,
                {
                    "heart_rate": 132,
                    "blood_pressure_sys": 88,
                    "blood_pressure_dia": 54,
                    "oxygen_saturation": 93,
                    "respiratory_rate": 28,
                    "temperature_c": 39.6,
                },
                9,
                1,
                [1, 1, 3, 2, 2],
                410,
                1,
                True,
                True,
                ["Possible septic shock", "Needs immediate monitored care"],
            )
        ],
        [
            _case(
                "med-peds-fever",
                "Three-year-old with fever and reduced oral intake",
                3,
                "carried by parent",
                "irritable but interactive",
                2,
                {
                    "heart_rate": 148,
                    "blood_pressure_sys": 96,
                    "blood_pressure_dia": 58,
                    "oxygen_saturation": 98,
                    "respiratory_rate": 26,
                    "temperature_c": 39.1,
                },
                13,
                0,
                [0, 1, 5, 4, 3],
                455,
                3,
                False,
                False,
                ["Needs pediatric review", "Resource pressure should not cause over-escalation"],
            )
        ],
        [
            _case(
                "med-gi-bleed",
                "Black stools, dizziness on standing, and one episode of coffee-ground vomiting",
                57,
                "walk-in",
                "lightheaded but oriented",
                4,
                {
                    "heart_rate": 118,
                    "blood_pressure_sys": 98,
                    "blood_pressure_dia": 62,
                    "oxygen_saturation": 97,
                    "respiratory_rate": 20,
                    "temperature_c": 36.9,
                },
                10,
                1,
                [1, 1, 4, 3, 2],
                386,
                2,
                False,
                True,
                ["Possible upper GI bleed", "Should receive monitored bed when available"],
            )
        ],
        [
            _case(
                "med-copd",
                "Known COPD with worsening cough, increasing sputum, and mild hypoxia",
                72,
                "wheelchair",
                "tired but coherent",
                3,
                {
                    "heart_rate": 110,
                    "blood_pressure_sys": 134,
                    "blood_pressure_dia": 78,
                    "oxygen_saturation": 91,
                    "respiratory_rate": 24,
                    "temperature_c": 38.1,
                },
                12,
                0,
                [0, 2, 5, 4, 2],
                438,
                3,
                False,
                False,
                ["Likely COPD infective exacerbation", "Needs timely treatment but not resus"],
            )
        ],
        [
            _case(
                "med-postpartum-bp",
                "Five days postpartum with severe headache, visual spots, and high blood pressure",
                29,
                "walk-in",
                "anxious but alert",
                7,
                {
                    "heart_rate": 102,
                    "blood_pressure_sys": 174,
                    "blood_pressure_dia": 112,
                    "oxygen_saturation": 99,
                    "respiratory_rate": 18,
                    "temperature_c": 36.8,
                },
                8,
                1,
                [0, 1, 4, 2, 2],
                267,
                2,
                False,
                True,
                ["Possible postpartum preeclampsia", "Needs urgent obstetric review and monitored bed"],
            )
        ],
        [
            _case(
                "med-hyperglycemia",
                "Type 1 diabetic with vomiting, abdominal pain, and very high glucose",
                24,
                "walk-in",
                "drowsy",
                5,
                {
                    "heart_rate": 126,
                    "blood_pressure_sys": 104,
                    "blood_pressure_dia": 68,
                    "oxygen_saturation": 98,
                    "respiratory_rate": 28,
                    "temperature_c": 37.3,
                },
                9,
                1,
                [1, 1, 4, 3, 1],
                351,
                2,
                False,
                True,
                ["Possible diabetic ketoacidosis", "Needs urgent assessment and monitored care"],
            )
        ],
    ],
    TaskName.HARD: [
        [
            _case(
                "hard-a1",
                "Unresponsive after collapse in waiting area",
                63,
                "walk-in collapse",
                "unresponsive",
                0,
                {
                    "heart_rate": 42,
                    "blood_pressure_sys": 70,
                    "blood_pressure_dia": 40,
                    "oxygen_saturation": 82,
                    "respiratory_rate": 8,
                    "temperature_c": 36.2,
                },
                7,
                0,
                [0, 1, 3, 2, 1],
                285,
                1,
                True,
                False,
                ["Immediate intervention needed", "Triggers resuscitation room escalation"],
            ),
            _case(
                "hard-a2",
                "Fever, rigors, confusion, and low urine output",
                74,
                "ambulance",
                "confused",
                5,
                {
                    "heart_rate": 132,
                    "blood_pressure_sys": 92,
                    "blood_pressure_dia": 58,
                    "oxygen_saturation": 94,
                    "respiratory_rate": 24,
                    "temperature_c": 39.4,
                },
                8,
                1,
                [1, 1, 3, 2, 1],
                292,
                2,
                False,
                True,
                ["Sepsis concern", "Monitored bed should be allocated if available"],
            ),
            _case(
                "hard-a3",
                "Severe abdominal pain radiating to back with vomiting",
                49,
                "walk-in",
                "alert",
                8,
                {
                    "heart_rate": 108,
                    "blood_pressure_sys": 104,
                    "blood_pressure_dia": 66,
                    "oxygen_saturation": 97,
                    "respiratory_rate": 22,
                    "temperature_c": 37.6,
                },
                9,
                1,
                [1, 1, 2, 3, 2],
                299,
                3,
                False,
                False,
                ["Urgent imaging likely", "Could deteriorate if delayed excessively"],
            ),
            _case(
                "hard-a4",
                "Ankle injury after sports practice",
                22,
                "walk-in",
                "alert",
                4,
                {
                    "heart_rate": 88,
                    "blood_pressure_sys": 122,
                    "blood_pressure_dia": 78,
                    "oxygen_saturation": 99,
                    "respiratory_rate": 16,
                    "temperature_c": 36.7,
                },
                10,
                0,
                [1, 1, 2, 3, 3],
                305,
                5,
                False,
                False,
                ["Stable musculoskeletal injury"],
            ),
            _case(
                "hard-a5",
                "Slurred speech and unilateral weakness",
                69,
                "ambulance",
                "confused",
                2,
                {
                    "heart_rate": 98,
                    "blood_pressure_sys": 168,
                    "blood_pressure_dia": 96,
                    "oxygen_saturation": 95,
                    "respiratory_rate": 20,
                    "temperature_c": 36.9,
                },
                11,
                1,
                [1, 2, 2, 3, 3],
                312,
                2,
                True,
                True,
                ["Possible acute stroke", "Time-critical neuro pathway"],
            ),
            _case(
                "hard-a6",
                "Postpartum heavy vaginal bleeding and dizziness",
                31,
                "wheelchair",
                "pale but responsive",
                7,
                {
                    "heart_rate": 136,
                    "blood_pressure_sys": 86,
                    "blood_pressure_dia": 50,
                    "oxygen_saturation": 96,
                    "respiratory_rate": 28,
                    "temperature_c": 36.4,
                },
                12,
                0,
                [1, 2, 2, 4, 3],
                319,
                1,
                True,
                False,
                ["Possible hemorrhagic shock", "Critical miss should heavily punish episode"],
            ),
        ],
        [
            _case(
                "hard-b1",
                "Motorbike collision with chest pain and shallow breathing",
                34,
                "ambulance",
                "agitated",
                9,
                {
                    "heart_rate": 128,
                    "blood_pressure_sys": 90,
                    "blood_pressure_dia": 60,
                    "oxygen_saturation": 89,
                    "respiratory_rate": 32,
                    "temperature_c": 36.1,
                },
                6,
                1,
                [0, 1, 2, 2, 1],
                180,
                1,
                True,
                True,
                ["Major trauma presentation"],
            ),
            _case(
                "hard-b2",
                "Dialysis patient with weakness and missed session",
                59,
                "wheelchair",
                "drowsy",
                2,
                {
                    "heart_rate": 54,
                    "blood_pressure_sys": 102,
                    "blood_pressure_dia": 62,
                    "oxygen_saturation": 96,
                    "respiratory_rate": 18,
                    "temperature_c": 36.8,
                },
                7,
                0,
                [1, 1, 2, 2, 1],
                187,
                2,
                False,
                False,
                ["Hyperkalemia risk despite stable oxygenation"],
            ),
            _case(
                "hard-b3",
                "Elderly fall with anticoagulant use and scalp laceration",
                82,
                "ambulance",
                "alert",
                6,
                {
                    "heart_rate": 102,
                    "blood_pressure_sys": 118,
                    "blood_pressure_dia": 72,
                    "oxygen_saturation": 97,
                    "respiratory_rate": 18,
                    "temperature_c": 36.5,
                },
                8,
                0,
                [1, 1, 2, 3, 1],
                194,
                3,
                False,
                False,
                ["Needs urgent CT consideration"],
            ),
            _case(
                "hard-b4",
                "Child with barking cough and mild stridor at rest",
                4,
                "carried by parent",
                "frightened",
                3,
                {
                    "heart_rate": 138,
                    "blood_pressure_sys": 94,
                    "blood_pressure_dia": 58,
                    "oxygen_saturation": 94,
                    "respiratory_rate": 30,
                    "temperature_c": 38.0,
                },
                10,
                1,
                [1, 1, 3, 3, 2],
                201,
                2,
                False,
                True,
                ["Potential airway deterioration"],
            ),
            _case(
                "hard-b5",
                "Dysuria and flank pain without hypotension",
                41,
                "walk-in",
                "alert",
                6,
                {
                    "heart_rate": 104,
                    "blood_pressure_sys": 126,
                    "blood_pressure_dia": 80,
                    "oxygen_saturation": 98,
                    "respiratory_rate": 18,
                    "temperature_c": 38.2,
                },
                12,
                1,
                [1, 2, 3, 4, 2],
                208,
                4,
                False,
                False,
                ["Likely pyelonephritis but currently stable"],
            ),
            _case(
                "hard-b6",
                "Chest tightness after peanut exposure with lip swelling",
                17,
                "walk-in",
                "anxious",
                5,
                {
                    "heart_rate": 144,
                    "blood_pressure_sys": 92,
                    "blood_pressure_dia": 60,
                    "oxygen_saturation": 90,
                    "respiratory_rate": 30,
                    "temperature_c": 36.8,
                },
                12,
                0,
                [1, 2, 3, 4, 2],
                214,
                1,
                True,
                False,
                ["Anaphylaxis concern", "Must escalate even without a free bed"],
            ),
        ],
    ],
}


def load_task_cases(task: TaskName, seed: int | None = None) -> List[dict]:
    episodes = TASK_EPISODES[task]
    index = 0 if seed is None else seed % len(episodes)
    return deepcopy(episodes[index])


def task_episode_count(task: TaskName) -> int:
    return len(TASK_EPISODES[task])


def iter_task_episodes() -> list[tuple[TaskName, int, list[dict]]]:
    episodes: list[tuple[TaskName, int, list[dict]]] = []
    for task, task_episodes in TASK_EPISODES.items():
        for seed, episode in enumerate(task_episodes):
            episodes.append((task, seed, deepcopy(episode)))
    return episodes
